# Generated by Django 5.1.4 on 2024-12-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='CBKNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=100)),
                ('contact_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('credate', models.DateTimeField(auto_now_add=True)),
                ('contact_type_id', models.IntegerField(blank=True, null=True)),
                ('del_status', models.CharField(default='0', max_length=1)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CBK Number',
                'verbose_name_plural': 'CBK Numbers',
                'db_table': 'CBK_NUMBERS',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SW_HR_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=90, unique=True)),
                ('staff_name', models.CharField(max_length=150)),
                ('job_desc', models.TextField()),
                ('organization_desc', models.CharField(max_length=450)),
                ('location_code', models.CharField(max_length=180)),
                ('grade_desc', models.CharField(max_length=180)),
                ('group_name', models.CharField(max_length=720)),
                ('nlc_type', models.CharField(max_length=450)),
                ('emp_type', models.CharField(max_length=33)),
            ],
            options={
                'verbose_name': 'SW HR V',
                'verbose_name_plural': 'SW HR V',
                'db_table': 'SW_HR_V',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('template_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CBKContacts',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('credate', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('empstatus', models.CharField(blank=True, max_length=200, null=True)),
                ('off_dir_id', models.BigIntegerField(blank=True, null=True)),
                ('off_ext_id', models.BigIntegerField(blank=True, null=True)),
                ('pascomm_id', models.BigIntegerField(blank=True, null=True)),
                ('defcomm_id', models.BigIntegerField(blank=True, null=True)),
                ('margala_id', models.BigIntegerField(blank=True, null=True)),
                ('confidential', models.BigIntegerField(default=0)),
                ('dashboard', models.BigIntegerField(default=0)),
                ('empstatus_id', models.BigIntegerField(blank=True, null=True)),
                ('curr_desg', models.CharField(blank=True, max_length=200, null=True)),
                ('curr_grade_id', models.BigIntegerField(default=0)),
                ('category', models.BigIntegerField(default=0)),
                ('descr', models.TextField(blank=True, null=True)),
                ('contact_addr', models.CharField(blank=True, max_length=500, null=True)),
                ('curr_sbu_id', models.BigIntegerField(default=0)),
                ('curr_dept_id', models.BigIntegerField(default=0)),
                ('curr_sec_id', models.BigIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('off_dir_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('staff_no', models.OneToOneField(db_column='staff_no', on_delete=django.db.models.deletion.CASCADE, to='smswebportal.sw_hr_v', to_field='staff_no')),
            ],
            options={
                'verbose_name': 'CBK Contact',
                'verbose_name_plural': 'CBK Contacts',
                'db_table': 'CBK_CONTACTS',
            },
        ),
        migrations.CreateModel(
            name='OutgoingSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('receiver_no', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smswebportal.group')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smswebportal.template')),
            ],
            options={
                'verbose_name': 'Outgoing SMS',
                'verbose_name_plural': 'Outgoing SMS',
            },
        ),
    ]
