# Generated by Django 5.1.4 on 2024-12-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbknumbers',
            old_name='contact_no',
            new_name='contactno',
        ),
    ]
