# Generated by Django 5.1.4 on 2024-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0002_rename_contact_no_cbknumbers_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbknumbers',
            name='contactno_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
