# Generated by Django 5.1.4 on 2024-12-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0004_cbkcontacts_mobile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingsms',
            name='template',
        ),
    ]
