# Generated by Django 5.1.4 on 2024-12-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0005_remove_outgoingsms_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingsms',
            name='group',
        ),
    ]
