# Generated by Django 5.1.4 on 2024-12-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0010_clean_receiver_no_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingsms',
            name='receiver_no',
            field=models.CharField(max_length=255),
        ),
    ]
