# Generated by Django 5.1.4 on 2024-12-30 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0011_alter_outgoingsms_receiver_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingsms',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
