# Generated by Django 5.1.4 on 2024-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0012_outgoingsms_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingsms',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
