# Generated by Django 5.1.4 on 2024-12-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0013_outgoingsms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingsms',
            name='status',
        ),
    ]
