# Generated by Django 5.1.4 on 2024-12-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0014_remove_outgoingsms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingsms',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
