# Generated by Django 5.1.4 on 2025-01-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0015_outgoingsms_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingsms',
            options={},
        ),
        migrations.RemoveField(
            model_name='outgoingsms',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='outgoingsms',
            name='receiver_no',
        ),
        migrations.RemoveField(
            model_name='outgoingsms',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='outgoingsms',
            name='status',
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='ERRORMSG',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='MSGTYPE',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='OPERATOR',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='RECEIVEDTIME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='RECEIVER',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='REFERENCE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='SENDER',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='SENTTIME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='STAT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='outgoingsms',
            table='OZEKIMESSAGEOUT',
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='MSG',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outgoingsms',
            name='STATUS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
