# Generated by Django 5.1.4 on 2025-01-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0016_alter_outgoingsms_options_remove_outgoingsms_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingsms',
            name='SENTTIME',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingsms',
            name='STATUS',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
