# Generated by Django 5.1.4 on 2025-01-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0017_alter_outgoingsms_senttime_alter_outgoingsms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingsms',
            name='SENTTIME',
        ),
    ]
