# Generated by Django 5.1.5 on 2025-04-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smswebportal', '0019_outgoingsms_senttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbknumbers',
            old_name='contactno',
            new_name='contact_no',
        ),
        migrations.AlterField(
            model_name='outgoingsms',
            name='SENTTIME',
            field=models.DateTimeField(auto_now_add=True, max_length=100, null=True),
        ),
    ]
